### PR TITLE
Fixed #477 : Corrected state for get and get by id command.

### LINKED ISSUE #477: "tink workflow get/get by id" command returns the incorrect state for workflows
"tink workflow get/get by id" command returns the incorrect state for workflows.
Right now it always returns state as STATE_PENDING for all the workflows which is incorrect because if a workflow is running it should have state as STATE_RUNNING and if finished successfully, it should have state as STATE_SUCCESSFUL.

## Expected Behaviour
"tink workflow get/get by id" command should return the current state for workflows.

## Current Behaviour
Right now it always returns state as STATE_PENDING for all the workflows which is incorrect.

## Possible Solution
Update the workflow state as soon as it started/finished/failed.

* Operating System Linux (Ubuntu 1804):

* How are you running Tinkerbell: Using Vagrant & VirtualBox

### PR DESCRIPTION
**Pull request by parauliya**
Signed-off-by: parauliya <aman@infracloud.io>

## Description
After this Fix user will get the correct state in `tink workflow get` and `tink workflow get <id>` 

## Why is this needed

Fixes: #477 

## How Has This Been Tested?
Tested Manually with Vagrant Setup.

## How are existing users impacted? What migration steps/scripts do we need?
No Impact.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

File: grpc-server/workflow.go [hunk 1]
```diff
@@ -279,3 +273,17 @@ func (s *server) ShowWorkflowEvents(req *workflow.GetRequest, stream workflow.Wo
 	metrics.CacheHits.With(labels).Inc()
 	return nil
 }
+
+func getWorkflowState(db db.Database, ctx context.Context, id string) workflow.State {
```
Comment (jacobweinstock) [inline grpc-server/workflow.go:277]: any chance you could add code comments on why this logic is needed?

File: grpc-server/workflow.go [hunk 2]
```diff
@@ -279,3 +273,17 @@ func (s *server) ShowWorkflowEvents(req *workflow.GetRequest, stream workflow.Wo
...
+	wfctx, _ := db.GetWorkflowContexts(ctx, id)
+	if wfctx.CurrentActionState != workflow.State_STATE_SUCCESS {
+		return wfctx.CurrentActionState
+	} else {
+		wfacts, _ := db.GetWorkflowActions(ctx, id)
```
Comment (jacobweinstock) [inline grpc-server/workflow.go:282]: doesnt `GetWorkflowContexts` already give `total_number_of_actions`? you could use that number and `current_action_index` to determine last action. It would save a database call.

**Review by jacobweinstock — COMMENTED** [review]
any chance you could add some tests?

File: grpc-server/workflow.go (hunk 2 above)
Comment (parauliya) [reply grpc-server/workflow.go:282]: Yeah, that is a good observation. Actually I did it beacuse the function `isLastAction()` was implemented in that way and asks for action lists as parameter. But yeah it is not required since we have total number of actions in `wfcontext` itself. I will change that. Thanks

File: grpc-server/workflow.go (hunk 1 above)
Comment (parauliya) [reply grpc-server/workflow.go:277]: Yeah sure I will add reason behind this logic as comment over this function.

**Review by thebsdbox — APPROVED** [review]

File: grpc-server/workflow.go [hunk 3]
```diff
@@ -279,3 +273,22 @@ func (s *server) ShowWorkflowEvents(req *workflow.GetRequest, stream workflow.Wo
...
+// For e.g. : If an action has Tailed or Timeout then the workflow state will also be
+// considered as Failed/Timeout. And If an action is successful then the workflow state
+// will be considered as Running until the last action of the workflow is executed successfully.
+
+func getWorkflowState(db db.Database, ctx context.Context, id string) workflow.State {
+	wfCtx, _ := db.GetWorkflowContexts(ctx, id)
+	if wfCtx.CurrentActionState != workflow.State_STATE_SUCCESS {
+		return wfCtx.CurrentActionState
+	} else {
+		//wfacts, _ := db.GetWorkflowActions(ctx, id)
```
Comment (jacobweinstock) [inline grpc-server/workflow.go:287]: should probably removed commented code

File: grpc-server/workflow.go [hunk 4]
```diff
@@ -279,3 +273,22 @@ func (s *server) ShowWorkflowEvents(req *workflow.GetRequest, stream workflow.Wo
 	metrics.CacheHits.With(labels).Inc()
 	return nil
 }
+
+// This function will provide the workflow state on the basis of the state of the actions
+// For e.g. : If an action has Tailed or Timeout then the workflow state will also be
```
Comment (jacobweinstock) [inline grpc-server/workflow.go:278]: NIT: misspelled word "Tailed" -> "Failed"

File: grpc-server/workflow.go [hunk 5]
```diff
@@ -181,6 +174,7 @@ func (s *server) ListWorkflows(_ *workflow.Empty, stream workflow.WorkflowServic
 			Hardware:  w.Hardware,
 			CreatedAt: w.CreatedAt,
 			UpdatedAt: w.UpdatedAt,
+			State:     getWorkflowState(s.db, stream.Context(), w.ID),
```
Comment (jacobweinstock) [inline grpc-server/workflow.go:177]: you're making 2 calls to `getWorkflowState`, this means 2 DB calls. You could call `getWorkflowState` just once (1 DB call) and store it to a variable for use in both locations.

**Review by jacobweinstock — COMMENTED** [review]
thanks for adding tests! so important to making the tink codebase less fragile!
made a few comments for your review.

File: grpc-server/workflow.go (hunk 5 above)
Comment (parauliya) [reply grpc-server/workflow.go:177]: I don't think it is possible to call `getWorkflowState` once and store it because the `workflow state` will change during the execution of a workflow which makes it dynamic. Therefore we have to fetch the `latest` value of a `workflow state`.

File: grpc-server/workflow.go (hunk 3 above)
Comment (parauliya) [reply grpc-server/workflow.go:287]: Removed.

File: grpc-server/workflow.go (hunk 4 above)
Comment (parauliya) [reply grpc-server/workflow.go:278]: Corrected

File: grpc-server/workflow.go (hunk 5 above)
Comment (jacobweinstock) [reply grpc-server/workflow.go:177]: Ah, apologies. You are right. For some reason I thought I saw two calls in a single function.

**Review by jacobweinstock — APPROVED** [review]
