### PR TITLE
Fix #363: Creation of template with the same name

### LINKED ISSUE #363: Creating a template sharing the same name as a deleted template causes an error
## Expected Behaviour

Templates can be successfully created even when it shares the same name as a deleted template.

## Current Behaviour

Due to the fact that templates are soft deleted and the recent change of name also being a unique field, creating a template sharing the same name as a deleted template returns this error:
```
rpc error: code = Unknown desc = INSERT: pq: duplicate key value violates unique constraint "template_name_key"
```

## Steps to Reproduce (for bugs)

1. create a unique constraint on name (if db isn't using the [latest tink migrations](https://github.com/tinkerbell/tink/blob/master/db/migration/202009171251-init-database.go#L22))
```
alter table template add constraint template_name_key unique (name);
```
2. create a workflow with a name
3. delete the workflow
4. create another workflow with the same name as in step 1

## Context

At first, I thought the soft delete was to be able to get workflow data even after the associated template has been (soft) deleted, but this is not the case. Therefore, what exactly is the purpose of soft deleting?

Granted, there is a workaround for this (e.g. use a UUID as part of the name), but it seems unintuitive that new templates have to take deleted templates into consideration. Also, the only way to see what names have already been used is going into the db.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 18.04

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
- Packet using Terraform (sandbox)
- running all the latest images as of 11/11
- added a unique constraint on template name in the db to match what's currently in the [tink migrations](https://github.com/tinkerbell/tink/blob/master/db/migration/202009171251-init-database.go#L22)
```
alter table template add constraint template_name_key unique (name);
```

* Link to your project or a code example to reproduce issue:
### Reproducing the error
```
/ # tink template create -n hello -p hello-world.yml
Created Template:  3119c312-2465-11eb-84af-0242ac130004
/ # tink template delete 3119c312-2465-11eb-84af-0242ac130004
/ # tink template create -n hello -p hello-world.yml
2020/11/11 21:31:18 rpc error: code = Unknown desc = INSERT: pq: duplicate key value violates unique constraint "template_name_key"
```

### Getting a workflow with a deleted associated template
```
/ # tink template list
+--------------------------------------+-----------------+-------------------------------+-------------------------------+
| TEMPLATE ID                          | TEMPLATE NAME   | CREATED AT                    | UPDATED AT                    |
+--------------------------------------+-----------------+-------------------------------+-------------------------------+
| f1e780de-2460-11eb-ad81-0242ac130004 | hello-new-world | 2020-11-11 21:00:35 +0000 UTC | 2020-11-11 21:00:35 +0000 UTC |
+--------------------------------------+-----------------+-------------------------------+-------------------------------+
/ # tink workflow list
+--------------------------------------+--------------------------------------+-----------------------------------+-------------------------------+-------------------------------+
| WORKFLOW ID                          | TEMPLATE ID                          | HARDWARE DEVICE                   | CREATED AT                    | UPDATED AT                    |
+--------------------------------------+--------------------------------------+-----------------------------------+-------------------------------+-------------------------------+
| d3de4f6a-246c-11eb-933f-0242ac130004 | f1e780de-2460-11eb-ad81-0242ac130004 | {"device_1": "b4:96:91:5f:a9:50"} | 2020-11-11 22:25:39 +0000 UTC | 2020-11-11 22:25:39 +0000 UTC |
+--------------------------------------+--------------------------------------+-----------------------------------+-------------------------------+-------------------------------+
/ # tink workflow get d3de4f6a-246c-11eb-933f-0242ac130004
version: 0.1
name: hello_world
global_timeout: 6000
tasks:
- name: "hello-world"
  worker: "b4:96:91:5f:a9:50"
  actions:
  - name: "hello-world"
    image: hello-world
    timeout: 90

/ # tink template delete f1e780de-2460-11eb-ad81-0242ac130004
/ # tink workflow get d3de4f6a-246c-11eb-933f-0242ac130004
2020/11/11 23:01:12 rpc error: code = Unknown desc = failed to get template with ID: f1e780de-2460-11eb-ad81-0242ac130004: sql: no rows in result set
```

Original reporter: Matt Burns

### PR DESCRIPTION
**Pull request by parauliya**
Signed-off-by: parauliya <aman@infracloud.io>

## Description

This PR will fix allow user to create a template with the same name after deleting it. Before this, it was not possible because of an issue also after deleting a template all the workflow which were created with that template before deleting it will be able to access the template since we template will be deleted softly. 

## Why is this needed

Fixes: #363 

## How Has This Been Tested?
Tested all the scenarios mentioned in the linked issue manually using vagrant setup.

## How are existing users impacted? What migration steps/scripts do we need?

Have written a migration script for db.

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [x] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

File: deploy/db/tinkerbell-init.sql [hunk 1]
```diff
@@ -13,7 +13,7 @@ CREATE INDEX IF NOT EXISTS idxgin_type ON hardware USING GIN (data JSONB_PATH_OP
 
 CREATE TABLE IF NOT EXISTS template (
         id UUID UNIQUE NOT NULL
-        , name VARCHAR(200) UNIQUE NOT NULL
+        , name VARCHAR(200) NOT NULL
```
Comment (gianarb) [inline deploy/db/tinkerbell-init.sql:16]: This is not used anymore. We use migrations now

https://github.com/tinkerbell/tink/tree/master/db/migration

You have to create a new migration file that ALTERS the current table

Comment (parauliya) [reply deploy/db/tinkerbell-init.sql]: Done

File: db/template.go [hunk 2]
```diff
@@ -14,7 +14,14 @@ import (
 
 // CreateTemplate creates a new workflow template
 func (d TinkDB) CreateTemplate(ctx context.Context, name string, data string, id uuid.UUID) error {
-	_, err := wflow.Parse([]byte(data))
```
Comment (gianarb) [inline db/template.go:17]: Why are you doing this?! If the template is not valid we should not go further. Can you revert or explain why you moved this down there?

File: db/db.go [hunk 3]
```diff
@@ -37,6 +37,7 @@ type hardware interface {
 type template interface {
 	CreateTemplate(ctx context.Context, name string, data string, id uuid.UUID) error
 	GetTemplate(ctx context.Context, fields map[string]string) (string, string, string, error)
+	GetTemplateForWorkflow(ctx context.Context, fields map[string]string) (string, string, string, error)
```
Comment (gianarb) [inline db/db.go:40]: I don't want to expose another API if not needed. Can you make `ListTemplates` smarter and remove this call?

**Review by gianarb — CHANGES_REQUESTED** [review]
A few comments and tests have to be written for this PR

File: db/template.go (hunk 2 above)
Comment (parauliya) [reply db/template.go:17]: Yes you are right. I moved it down by mistake. Will fix it.

File: db/template.go [hunk 4]
```diff
@@ -74,6 +80,35 @@ func (d TinkDB) GetTemplate(ctx context.Context, fields map[string]string) (stri
...
+	if err != nil {
+		return "", "", "", errors.Wrap(err, "failed to get template")
+	}
+
+	query := `
+	SELECT id, name, data
+	FROM template
+	WHERE
+		` + getCondition + `
+		created_at IS NOT NULL
```
[the remark this answers is not in the document]
Comment (parauliya) [reply db/template.go:95]: This code has been discarded.

File: db/db.go (hunk 3 above)
Comment (parauliya) [reply db/db.go:40]: I have made `GetTemplate` API smarter and removed this new API.

File: db/template.go (hunk 2 above)
Comment (parauliya) [reply db/template.go]: Done

File: db/db.go (hunk 3 above)
Comment (parauliya) [reply db/db.go]: Done

**Review by gianarb — DISMISSED** [review]
It is good for me. Thank you for taking the time to add coverage.

I have to say, the more I look at the database package, and more I think we are doing something wrong in there. I would really like to write it in a more consistent way. But it is not part of this work for sure :D

**Review by kdeng3849 — APPROVED** [review]

File: db/migration/202012041103-remove-unique-constraints.go [hunk 5]
```diff
@@ -0,0 +1,12 @@
+package migration
+
+import migrate "github.com/rubenv/sql-migrate"
+
+func Get202012041103() *migrate.Migration {
+	return &migrate.Migration{
+		Id: "202010221010-remove-unique-index",
```
Comment (ryli17) [inline db/migration/202012041103-remove-unique-constraints.go:7]: The id is wrong. Please use the same timestamp in the function name.

File: db/template.go [hunk 6]
```diff
@@ -19,11 +19,17 @@ func (d TinkDB) CreateTemplate(ctx context.Context, name string, data string, id
 		return err
 	}
 
+	fields := map[string]string{
+		"name": name,
+	}
+	_, _, _, err = d.GetTemplate(ctx, fields, false)
```
Comment (ryli17) [inline db/template.go:25]: This query is not in the same transaction as the following insert DML, thus is not concurrent safe.
